version: '3.9'
services:
 mysql1:
  image: mysql:5.7
  container_name: dbsql
  volumes:
   - ./sqlfolder:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: admin
  healthcheck:
   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-padmin"]
   timeout: 20s # Timeout for each health checking.
   retries: 10 # Hou many times retries.
 node1:
  build: ./backend
  container_name: backend
  ports:
   - "8080:8080"
  volumes:
   - ./backend:/usr/src/app
  depends_on:
   mysql1: 
    condition: service_healthy
  stdin_open: true
  tty: true
 node2:
  build: ./Frontend
  container_name: client
  ports:
   - "3000:3000"
  volumes:
   - ./Frontend/client:/usr/src/app
  depends_on:
   mysql1: 
    condition: service_healthy
  stdin_open: true
  tty: true